import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderApp } from "./layouts/Header";
import { FooterApp } from "./layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="google-site-verification" content="nZdFbIayBvnKp0U3FjLmrM6rbOlEwAJ2qn4ZNjSWluM" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderApp />

        {children}
        <FooterApp />
      </body>
    </html>
  );
}
